### ISSUE TITLE
Build with gradle wrapper fails on fresh checkout

### ISSUE THREAD

**Issue by ploober** [erichaagdev/KappaBot#19]
I think we need to set gradle wrapper back to a proper release version. I'm pretty sure this one is a snapshot that is no longer available.

```
$ git clone https://github.com/Gorlah/KappaBot.git
Cloning into 'KappaBot'...
remote: Enumerating objects: 402, done.
remote: Counting objects: 100% (402/402), done.
remote: Compressing objects: 100% (227/227), done.
remote: Total 1204 (delta 157), reused 311 (delta 93), pack-reused 802
Receiving objects: 100% (1204/1204), 2.79 MiB | 17.65 MiB/s, done.
Resolving deltas: 100% (522/522), done.
$ cd KappaBot
$ ./gradlew
Downloading https://services.gradle.org/distributions-snapshots/gradle-6.1-20191115232337+0000-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-6.1-20191115232337+0000-bin.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1923)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

**Comment by erichaagdev** [comment]
This will be addressed by #21
